name: NAS user creation
description: NAS user creation
title: "NAS User creation"
labels: ["nas_user_creation"]
assignees:
  - agricolamz
type: nas_user_creation
body:
  - type: input
    id: user_name
    attributes:
      label: Вставьте, пожалуйста, Ваше имя
      placeholder: Пётр Карлович Услар
    validations:
      required: false
